### ISSUE TITLE
refined liquids name?

### ISSUE THREAD

**Issue by d3y419** [bc3LC/gcamreport#10]
trn_pass_road_LDV_4W,refined liquids transport,Car,,,1
trn_pass_road_LDV_4W,refined liquids transport,Large Car and Truck,,,1
trn_pass_road_LDV_4W,refined liquids transport,Mini Car,,,1

inst/extdata/mappings/transport_final_en_map.csv

I'm trying to understand what's going on here. If I understand this correctly, from GCAM 6 to GCAM 7, are you changing the "refined liquids" names into several different products? Is this supposed to be different from the standard GCAM 7 release?

More generally, I think the current structure could benefit from "other" category. If the left join can't find the exact fuel name, sector name, etc. then it should automatically stuff them in the "other category". Then the user would know where to fix it. 

Otherwise, slightly different fuel names and sector names would simply disappear (e.g. refined liquids vs refined liquids transport), and unsuspecting user would report with missing data. We could also put in a checksum at the end to make sure the total final energy matches the sum of final energy. (These are good ideas, but @russellhz can tell you that I lack skills to implement it).

Thanks!

CC: @coreanjs @AhmedM27

**Comment by klau506** [comment]
Hi @d3y419 ,

Thank you for your post! The issue you are encountering is due to a special study mapping modification that has been merged (by mistake) to the core version of the pkg. We will try to fix it ASAP, as well as to implement your suggestions :)

Keep you posted,
Best,
Clàudia

**Comment by klau506** [comment]
Hi @d3y419 ,

Sorry for the delay. We have just fixed the `transport_final_en_map.csv` map. In line with the "other" category you suggested, we are working on a new pkg version that checks and warns the users of possible errors when joining datasets or performing other manipulations. Hope to have it soon!

Best,
Clàudia

CC: @coreanjs @AhmedM27

**Comment by d3y419** [comment]
Awesome! You are the best!
