### ISSUE TITLE
stuck at load all

### ISSUE THREAD

**Issue by d3y419** [bc3LC/gcamreport#7]
I get stuck at load all. do i need to specify prj even before library?

![image](https://github.com/bc3LC/gcamreport/assets/23386151/c1637942-268f-4921-80a7-909eea721f31)

**Comment by d3y419** [comment]
@russellhz help!

**Comment by russellhz** [comment]
Hi Haewon, this looks weird, you definitely shouldn't need to specify anything before loading. @klau506  any ideas?

**Comment by klau506** [comment]
Dear @d3y419,

I'm sorry you experience this error. I can't reproduce it; I've tried in some devices the `devtools::load_all()` command and worked fine. So maybe, try the following:
1. Check you have the most updated version of the `gcamreport` package.
2. Make sure you opened the `gcamreport.Rproj` in Rstudio and that your `getwd()` path points to the `gcamreport` cloned folder.
3.  _Source_ the `R/function.R` file and then try again the `devtools::load_all()` command.

If still this does not work, you can try to reinstall the package either through  the R [light](https://github.com/bc3LC/gcamreport?tab=readme-ov-file#with-R-light-mode-installation) or [full](https://github.com/bc3LC/gcamreport?tab=readme-ov-file#with-R-full-mode-installation) mode installation, or provide us the `sessionInfo()` to better check the bug.

Hope this works,
Best,
Clàudia

**Comment by d3y419** [comment]
Sorry, false alarm! we added a /getquery/ outside the functions bracket. and that was the reason for the error. Once we moved the getquery command inside a function, it worked!
Thanks a lot for developing this package! You saved me so many hours of manual copypasta.
